version: "3.7"
services:
  redis:
    image: redis:6.2.0
    expose:
      - 6379
  shell:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      REDIS_HOST: redis
    volumes:
      - .:/src
    depends_on:
      - redis
